"""
Reads the .geojson file you exported from scripts/draw_map.py and applies
it to the project:
  - The smallest rectangle you drew becomes the reserve boundary.
  - A second, larger rectangle (if you drew one) becomes the buffer zone
    boundary. If you only drew one rectangle, a buffer zone is
    auto-generated by expanding the reserve boundary outward by
    RESERVE_BUFFER_WIDTH_KM (src/config.py).
  - Each polygon you drew becomes that tiger's home range, with 20
    sighting points scattered inside it and written to the database,
    matched against real ATRW photos where available (Swastik uses his
    dedicated real-photo folder; the other tigers use data/samples/best_tigers/).

Run scripts/draw_map.py first to produce the .geojson file this reads.
"""

import json
import glob
import math
import os
import random
from datetime import datetime, timedelta
from pathlib import Path

from shapely.geometry import shape, mapping, Point

from src.db import get_connection
from src.classification.blank_detector import classify_image
from src.config import BASE_DIR, RESERVE_BUFFER_WIDTH_KM

BEST_TIGERS_DIR = BASE_DIR / "data" / "samples" / "best_tigers"
SWASTIK_PHOTOS_DIR = BASE_DIR / "data" / "samples" / "swastik"
BOUNDARY_PATH = BASE_DIR / "data" / "samples" / "pench_boundary_approx.geojson"
BUFFER_PATH = BASE_DIR / "data" / "samples" / "pench_buffer_approx.geojson"

TIGER_ORDER = ["Virat", "Bheem", "Yuvraj", "Bajirao", "Machli", "Ustad", "Jai", "Sultan", "Collarwali", "Swastik"]
TIGER_ID_MAP = {
    "Virat": "T-271", "Bheem": "T-201", "Yuvraj": "T-259", "Bajirao": "T-273",
    "Machli": "T-250", "Ustad": "T-256", "Jai": "T-171", "Sultan": "T-247",
    "Collarwali": "T-238", "Swastik": "T-SWASTIK",
}
KM_PER_DEG_LAT = 111.0


def km_per_deg_lon(lat):
    return 111.0 * math.cos(math.radians(lat))


def find_downloaded_file():
    downloads = str(Path.home() / "Downloads")
    candidates = glob.glob(os.path.join(downloads, "*vyaghra_drawn_shapes*.geojson")) + \
                 glob.glob(os.path.join(downloads, "*.geojson"))
    if not candidates:
        return None
    return max(candidates, key=os.path.getmtime)  # most recently downloaded


def polygon_area_sq_km(polygon):
    coords = list(polygon.exterior.coords)
    ref_lon, ref_lat = coords[0]
    km_coords = [((lon - ref_lon) * km_per_deg_lon(ref_lat), (lat - ref_lat) * KM_PER_DEG_LAT) for lon, lat in coords]
    return abs(sum(km_coords[i][0] * km_coords[i + 1][1] - km_coords[i + 1][0] * km_coords[i][1]
                    for i in range(len(km_coords) - 1))) / 2.0


def scatter_points_in_polygon(polygon, n_points=20, seed_val=0):
    rng = random.Random(seed_val)
    minx, miny, maxx, maxy = polygon.bounds
    points = []
    attempts = 0
    while len(points) < n_points and attempts < n_points * 50:
        p = Point(rng.uniform(minx, maxx), rng.uniform(miny, maxy))
        if polygon.contains(p):
            points.append((p.y, p.x))  # (lat, lon)
        attempts += 1
    return points


def is_rectangle_like(geom):
    """A shape drawn with Leaflet.draw's rectangle tool has exactly 5
    coordinate pairs (4 corners + closing point). Freeform tiger
    territory polygons will essentially never happen to have exactly 5
    vertices, so this is a reliable enough heuristic without needing to
    check angles."""
    coords = list(geom.exterior.coords)
    return len(coords) == 5


def build_auto_buffer(reserve_geom):
    """Expands the reserve boundary outward by RESERVE_BUFFER_WIDTH_KM to
    produce a buffer zone polygon, used when the user didn't hand-draw a
    second, larger rectangle."""
    centroid = reserve_geom.centroid
    lat = centroid.y
    deg_buffer_lat = RESERVE_BUFFER_WIDTH_KM / KM_PER_DEG_LAT
    deg_buffer_lon = RESERVE_BUFFER_WIDTH_KM / km_per_deg_lon(lat)
    # Simple degree-space buffer (not a true geodesic buffer) — good enough
    # at the scale of a single reserve, consistent with the rest of this
    # module's flat-earth-approximation math (see polygon_area_sq_km above).
    deg_buffer = (deg_buffer_lat + deg_buffer_lon) / 2.0
    return reserve_geom.buffer(deg_buffer, join_style=2)  # join_style=2 -> mitred/rectangular corners


def images_dir_for(tiger_name):
    """Real ATRW photo folder for a given tiger, or Swastik's dedicated
    real-photo folder."""
    if tiger_name == "Swastik":
        return SWASTIK_PHOTOS_DIR
    tiger_id = TIGER_ID_MAP[tiger_name]
    return BEST_TIGERS_DIR / f"tiger_{tiger_id.split('-')[1]}"


def main():
    file_path = input("Path to your downloaded .geojson file (press Enter to auto-detect from Downloads): ").strip()
    if not file_path:
        file_path = find_downloaded_file()
        if not file_path:
            print("Could not find a .geojson file in your Downloads folder. Please provide the path manually.")
            return
        print(f"Using: {file_path}")

    with open(file_path) as f:
        data = json.load(f)

    features = data["features"]
    print(f"\nFound {len(features)} drawn shape(s).")

    rectangle_features = []
    polygon_features = []

    for feat in features:
        geom = shape(feat["geometry"])
        if is_rectangle_like(geom):
            rectangle_features.append(geom)
        else:
            polygon_features.append(geom)

    # Smallest rectangle = reserve boundary. A second, larger one (if drawn)
    # = the user's own buffer zone boundary.
    rectangle_features.sort(key=lambda g: g.area)
    reserve_geom = rectangle_features[0] if rectangle_features else None
    buffer_geom = rectangle_features[1] if len(rectangle_features) > 1 else None

    if reserve_geom is None:
        print("WARNING: no rectangle detected — skipping boundary/buffer update. "
              "Draw a rectangle and export again if needed.")
    else:
        boundary_geojson = {
            "type": "FeatureCollection",
            "features": [{
                "type": "Feature",
                "properties": {"name": "Pench Tiger Reserve boundary (user-drawn)"},
                "geometry": mapping(reserve_geom),
            }],
        }
        with open(BOUNDARY_PATH, "w") as f:
            json.dump(boundary_geojson, f, indent=2)
        print(f"Reserve boundary updated from your drawn rectangle -> {BOUNDARY_PATH}")

        if buffer_geom is None:
            buffer_geom = build_auto_buffer(reserve_geom)
            print(f"No second rectangle drawn — auto-generated a {RESERVE_BUFFER_WIDTH_KM} km buffer zone.")
        else:
            print("Second (larger) rectangle detected — using it as your hand-drawn buffer zone.")

        buffer_geojson = {
            "type": "FeatureCollection",
            "features": [{
                "type": "Feature",
                "properties": {"name": "Pench Tiger Reserve buffer zone"},
                "geometry": mapping(buffer_geom),
            }],
        }
        with open(BUFFER_PATH, "w") as f:
            json.dump(buffer_geojson, f, indent=2)
        print(f"Buffer zone saved -> {BUFFER_PATH}")
        print("Run src/alerts/rules.py (or the full pipeline) after this to start getting "
              "buffer/reserve-exit alerts based on it.")

    if len(polygon_features) == 0:
        print("\nNo territory polygons found — nothing to import for tigers.")
        conn = None
    elif len(polygon_features) > len(TIGER_ORDER):
        print(f"\nWARNING: found {len(polygon_features)} polygons but only {len(TIGER_ORDER)} known tigers. "
              f"Extra polygons will be asked about individually.")

    if not polygon_features:
        return

    conn = get_connection()
    conn.execute("INSERT INTO runs (run_timestamp) VALUES (datetime('now'))")
    conn.commit()
    run_id = conn.execute("SELECT last_insert_rowid()").fetchone()[0]

    print("\nMatching your drawn polygons to tigers (in the order you drew them):")
    print(f"(Expected order: {', '.join(TIGER_ORDER)})\n")
    for i, poly in enumerate(polygon_features):
        default_name = TIGER_ORDER[i] if i < len(TIGER_ORDER) else None
        centroid = poly.centroid
        prompt = f"  Polygon {i+1} (centroid ~{centroid.y:.4f},{centroid.x:.4f}) -> tiger name"
        prompt += f" [{default_name}]: " if default_name else ": "
        chosen = input(prompt).strip() or default_name

        if chosen not in TIGER_ID_MAP:
            print(f"    Unknown tiger name '{chosen}', skipping this polygon.")
            continue

        tiger_id = TIGER_ID_MAP[chosen]
        area = polygon_area_sq_km(poly)
        points = scatter_points_in_polygon(poly, n_points=20, seed_val=i + 1)

        conn.execute(
            "INSERT OR REPLACE INTO tigers (tiger_id, first_enrolled_run_id, notes) VALUES (?, ?, ?)",
            (tiger_id, run_id, chosen),
        )
        conn.commit()

        tiger_folder = images_dir_for(chosen)
        images = sorted(tiger_folder.glob("*.jpg")) if tiger_folder.exists() else []
        if not images and tiger_folder.exists():
            images = sorted([p for p in tiger_folder.glob("*") if p.suffix.lower() in (".jpg", ".jpeg", ".png", ".jfif")])

        # Replacing this tiger's territory means their old sightings/points
        # would otherwise pile up alongside the new hand-drawn ones — clear
        # prior sightings tied to this tiger's synthetic/scattered points
        # (never touches other tigers) before inserting the fresh set.
        old_image_ids = [row[0] for row in conn.execute(
            "SELECT image_id FROM sightings WHERE tiger_id = ?", (tiger_id,)
        ).fetchall()]
        conn.execute("DELETE FROM sightings WHERE tiger_id = ?", (tiger_id,))
        if old_image_ids:
            conn.executemany("DELETE FROM images WHERE image_id = ? AND original_path = 'synthetic'",
                              [(iid,) for iid in old_image_ids])
        conn.execute("DELETE FROM occupancy_snapshots WHERE tiger_id = ?", (tiger_id,))
        conn.commit()

        for j, (plat, plon) in enumerate(points):
            if images:
                img_path = images[j % len(images)]
                result = classify_image(str(img_path))
                conf = result["confidence"]
                original_path = str(img_path)
            else:
                conf = 0.85
                original_path = "synthetic"

            fake_dt = datetime.now() - timedelta(days=random.randint(0, 45))
            cursor = conn.execute(
                """INSERT INTO images (original_path, station_id, capture_timestamp, timestamp_confidence,
                                        gps_lat, gps_lon, classification, classification_confidence, run_id)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (original_path, "ST-012", fake_dt.isoformat(), "synthetic", plat, plon, "subject", conf, run_id),
            )
            conn.commit()
            image_id = cursor.lastrowid

            conn.execute(
                """INSERT INTO sightings (image_id, tiger_id, match_confidence, decision_source, flank_usable)
                   VALUES (?, ?, ?, ?, ?)""",
                (image_id, tiger_id, conf, "human", 1),
            )
            conn.commit()

        conn.execute(
            """INSERT INTO occupancy_snapshots
               (tiger_id, run_id, centroid_lat, centroid_lon, area_sq_km, home_range_geojson, station_list)
               VALUES (?, ?, ?, ?, ?, ?, ?)""",
            (tiger_id, run_id, centroid.y, centroid.x, area, json.dumps(mapping(poly)), ""),
        )
        conn.commit()
        img_note = f"{len(images)} real photos" if images else "no real photos found, using synthetic placeholders"
        print(f"    -> {chosen}: area={area:.1f} sq km, {len(points)} points scattered inside your drawn shape ({img_note})")

    conn.close()
    print(f"\nDone. Run ID: {run_id}.")
    print("Next: python -m src.alerts.rules   (checks the buffer zone + movement history and raises alerts)")
    print("Then: python -m scripts.generate_html_dashboard   (rebuilds the dashboard with your hand-drawn territories)")


if __name__ == "__main__":
    main()