"""
Generates tiger territories using a correlated random walk — the standard
ecological model for real animal foraging movement (mostly continuing in a
consistent direction with occasional turns, unlike pure random noise or a
fixed mathematical formula shape).

The territory boundary is generated by buffering the actual walked path
into a polygon (like a thick, wobbly highlighter stroke along the route) —
this always produces a valid, non-empty, organic shape, unlike a concave
hull which can fail silently on sparse or clustered points.

Every step of the walk is checked against the real reserve boundary and
lake polygons via point-in-polygon tests, so no tiger can ever be placed
outside the reserve or inside the reservoir — enforced in code, not just
visually approximated.
"""

import json
import math
import random
from datetime import datetime, timedelta

from shapely import Point
from shapely.geometry import LineString, mapping, shape

from src.db import get_connection
from src.classification.blank_detector import classify_image
from src.config import BASE_DIR

BEST_TIGERS_DIR = BASE_DIR / "data" / "samples" / "best_tigers"
KM_PER_DEG_LAT = 111.0


def km_per_deg_lon(lat):
    return 111.0 * math.cos(math.radians(lat))


with open(BASE_DIR / "data" / "samples" / "pench_boundary_approx.geojson") as f:
    _boundary_data = json.load(f)
    RESERVE_POLYGON = shape(_boundary_data["features"][0]["geometry"])

with open(BASE_DIR / "data" / "samples" / "pench_lake_approx.geojson") as f:
    _lake_data = json.load(f)
    LAKE_POLYGON = shape(_lake_data["features"][0]["geometry"])

print(f"Reserve polygon valid: {RESERVE_POLYGON.is_valid}, area: {RESERVE_POLYGON.area:.4f} sq deg")
print(f"Lake polygon valid: {LAKE_POLYGON.is_valid}")
_test_lat, _test_lon = 21.6716, 79.3033  # official park center — must be inside reserve
print(f"Official park center inside reserve: {RESERVE_POLYGON.contains(Point(_test_lon, _test_lat))}")

def is_valid_point(lat, lon):
    p = Point(lon, lat)
    return RESERVE_POLYGON.contains(p) and not LAKE_POLYGON.contains(p)

TIGER_PROFILES = {
    # West of the lake (lon < 79.265, full lat range available)
    "271": {"name": "Virat",      "start": (21.680, 79.220), "n_steps": 42, "step_mean_km": 0.35, "turn_std_deg": 25, "seed": 11},
    "201": {"name": "Bheem",      "start": (21.700, 79.240), "n_steps": 45, "step_mean_km": 0.35, "turn_std_deg": 45, "seed": 22},
    "259": {"name": "Yuvraj",     "start": (21.660, 79.230), "n_steps": 40, "step_mean_km": 0.35, "turn_std_deg": 15, "seed": 33},

    # East of the lake (lon > 79.315, full lat range available)
    "273": {"name": "Bajirao",    "start": (21.680, 79.340), "n_steps": 42, "step_mean_km": 0.35, "turn_std_deg": 55, "seed": 44},
    "250": {"name": "Machli",     "start": (21.700, 79.350), "n_steps": 44, "step_mean_km": 0.35, "turn_std_deg": 30, "seed": 55},
    "256": {"name": "Ustad",      "start": (21.660, 79.335), "n_steps": 40, "step_mean_km": 0.35, "turn_std_deg": 40, "seed": 66},

    # North of the lake (lat > 21.735, lake doesn't reach this far up at any longitude)
    "171": {"name": "Jai",        "start": (21.760, 79.240), "n_steps": 40, "step_mean_km": 0.35, "turn_std_deg": 20, "seed": 77},
    "247": {"name": "Sultan",     "start": (21.760, 79.300), "n_steps": 40, "step_mean_km": 0.35, "turn_std_deg": 50, "seed": 88},
    "238": {"name": "Collarwali", "start": (21.770, 79.340), "n_steps": 40, "step_mean_km": 0.35, "turn_std_deg": 35, "seed": 99},
}
NEAREST_STATION = "ST-012"


def correlated_random_walk(start_lat, start_lon, n_steps, step_mean_km, turn_std_deg, seed_val):
    """
    Simulates real foraging movement (correlated random walk). Every
    candidate step is checked against the actual reserve/lake polygons;
    invalid steps are retried with a smaller, redirected step rather than
    just clamped to a box edge.
    """
    rng = random.Random(seed_val)
    lat, lon = start_lat, start_lon
    heading = rng.uniform(0, 360)
    points = [(lat, lon)]

    for _ in range(n_steps):
        placed = False
        attempts = 0
        while not placed and attempts < 15:
            turn = rng.gauss(0, turn_std_deg)
            candidate_heading = (heading + turn) % 360
            step_km = max(0.05, rng.expovariate(1.0 / step_mean_km)) * (0.6 ** attempts)

            rad = math.radians(candidate_heading)
            dlat = (step_km * math.cos(rad)) / KM_PER_DEG_LAT
            dlon = (step_km * math.sin(rad)) / km_per_deg_lon(lat)
            new_lat, new_lon = lat + dlat, lon + dlon

            if is_valid_point(new_lat, new_lon):
                lat, lon, heading = new_lat, new_lon, candidate_heading
                points.append((lat, lon))
                placed = True
            else:
                heading = (heading + 180 + rng.uniform(-40, 40)) % 360
                attempts += 1

        if not placed:
            # Couldn't find a valid step after 15 tries (rare, near a tight
            # corner) — just stay put this step rather than crash.
            points.append((lat, lon))

    return points


def seed():
    conn = get_connection()
    conn.execute("INSERT INTO runs (run_timestamp) VALUES (datetime('now'))")
    conn.commit()
    run_id = conn.execute("SELECT last_insert_rowid()").fetchone()[0]

    for real_tiger_id, profile in TIGER_PROFILES.items():
        tiger_folder = BEST_TIGERS_DIR / f"tiger_{real_tiger_id}"
        if not tiger_folder.exists():
            print(f"Skipping {real_tiger_id}: folder not found")
            continue

        vyaghra_tiger_id = f"T-{real_tiger_id}"
        display_name = profile["name"]
        start_lat, start_lon = profile["start"]

        if not is_valid_point(start_lat, start_lon):
            print(f"WARNING: {display_name}'s start point is invalid (outside reserve or in lake) — skipping")
            continue

        conn.execute(
            "INSERT OR REPLACE INTO tigers (tiger_id, first_enrolled_run_id, notes) VALUES (?, ?, ?)",
            (vyaghra_tiger_id, run_id, display_name),
        )
        conn.commit()

        walk_points = correlated_random_walk(
            start_lat, start_lon,
            profile["n_steps"], profile["step_mean_km"], profile["turn_std_deg"], profile["seed"],
        )

        # Buffer the walked path into a polygon — always valid, organic,
        # and directly reflects the tiger's actual simulated movement.
        path_line = LineString([(lon, lat) for lat, lon in walk_points])
        rng_width = random.Random(profile["seed"] + 777)
        buffer_deg = rng_width.uniform(0.010, 0.022)
        hull = path_line.buffer(buffer_deg, cap_style=1, join_style=1, resolution=8)
        hull = hull.simplify(0.002, preserve_topology=True)

        # Compute area in sq km via local equal-area approximation.
        area = 0.0
        if hull.geom_type == "Polygon" and not hull.is_empty:
            ref_lon, ref_lat = hull.exterior.coords[0]
            km_coords = [
                ((lon - ref_lon) * km_per_deg_lon(ref_lat), (lat - ref_lat) * KM_PER_DEG_LAT)
                for lon, lat in hull.exterior.coords
            ]
            area = abs(sum(
                km_coords[i][0] * km_coords[i + 1][1] - km_coords[i + 1][0] * km_coords[i][1]
                for i in range(len(km_coords) - 1)
            )) / 2.0
        elif hull.geom_type == "MultiPolygon" and not hull.is_empty:
            # Rare edge case: buffered path split into disconnected pieces.
            largest = max(hull.geoms, key=lambda g: g.area)
            hull = largest
            ref_lon, ref_lat = hull.exterior.coords[0]
            km_coords = [
                ((lon - ref_lon) * km_per_deg_lon(ref_lat), (lat - ref_lat) * KM_PER_DEG_LAT)
                for lon, lat in hull.exterior.coords
            ]
            area = abs(sum(
                km_coords[i][0] * km_coords[i + 1][1] - km_coords[i + 1][0] * km_coords[i][1]
                for i in range(len(km_coords) - 1)
            )) / 2.0

        rng = random.Random(profile["seed"] + 500)
        sighting_points = rng.sample(walk_points, min(20, len(walk_points)))

        images = sorted(tiger_folder.glob("*.jpg"))
        print(f"\n{display_name} ({vyaghra_tiger_id}): {len(walk_points)}-step walk, "
              f"{len(sighting_points)} sightings, area={area:.2f} sq km, geom_type={hull.geom_type}")

        for i, (plat, plon) in enumerate(sighting_points):
            img_path = images[i % len(images)]
            result = classify_image(str(img_path))
            fake_dt = datetime.now() - timedelta(days=random.randint(0, 45))

            cursor = conn.execute(
                """INSERT INTO images (original_path, station_id, capture_timestamp, timestamp_confidence,
                                        gps_lat, gps_lon, classification, classification_confidence, run_id)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (str(img_path), NEAREST_STATION, fake_dt.isoformat(), "synthetic",
                 plat, plon, result["label"], result["confidence"], run_id),
            )
            conn.commit()
            image_id = cursor.lastrowid

            conn.execute(
                """INSERT INTO sightings (image_id, tiger_id, match_confidence, decision_source, flank_usable)
                   VALUES (?, ?, ?, ?, ?)""",
                (image_id, vyaghra_tiger_id, result["confidence"], "human", 1),
            )
            conn.commit()

        if area > 0 and hull.geom_type == "Polygon" and not hull.is_empty:
            geojson_polygon = mapping(hull)
            conn.execute(
                """INSERT INTO occupancy_snapshots
                   (tiger_id, run_id, centroid_lat, centroid_lon, area_sq_km, home_range_geojson, station_list)
                   VALUES (?, ?, ?, ?, ?, ?, ?)""",
                (vyaghra_tiger_id, run_id, start_lat, start_lon, area, json.dumps(geojson_polygon), ""),
            )
            conn.commit()
        else:
            print(f"  WARNING: {display_name}'s polygon is empty/invalid — no occupancy snapshot saved")

    conn.close()
    print(f"\nSeeding complete. Run ID: {run_id}")
    return run_id


if __name__ == "__main__":
    seed()